### PR TITLE
Signature field

### PR DESCRIPTION
**Pull request by squallstar**
img

ref https://github.com/Fliplet/fliplet-studio/issues/2444

### CODE REVIEW

**Comment by tonytlwu** [comment]
Needs a **X Clear** link to clear the signature field

https://github.com/Fliplet/fliplet-studio/issues/2444#issuecomment-378618274

**Comment by squallstar** [comment]
@tonytlwu thanks, added:

gif

**Comment by squallstar** [comment]
@tonytlwu I also added some style so that the canvas is visible in "edit mode": 

img

**Comment by squallstar** [comment]
@tonytlwu shall we put this on staging=

**Comment by ibroom** [comment]
A client has asked if this field can be used in landscape e.g. you can tap 'Full screen' or a zoom icon so a user has the full horizontal screen to sign instead of just a small area.

**Comment by squallstar** [comment]
@tonytlwu ^

**Pull request merged**
