### PR TITLE
public method to set up form field options

### PR DESCRIPTION
**Pull request by squallstar**
```js
form.field('foo').options([ 'hello', 'world'  ]);

form.field('foo').options([ { id: 'hello', disabled: true }, { value: 'world' }  ]);
```

### CODE REVIEW

**Comment by tonytlwu** [comment]
@squallstar Can you confirm that this works for all following field types?

- [ ] Checkboxes
- [ ] Radio buttons
- [ ] Dropdowns

**Comment by squallstar** [comment]
@tonytlwu yes although the `disabled` prop is only implemented on dropdowns.

**Comment by tonytlwu** [comment]
@squallstar 

1. Is it much more work to have `disabled` working for the other 2 types too?
1. In this case, I have a slight preference to use `value` instead of `id`

**Comment by squallstar** [comment]
@tonytlwu 

1. I would skip this for now since nobody is asking for it hence it's not justified work. Yes, it will take some time to be tested properly across all use cases and platforms.
2. The form builder internally uses `id` because **Vue** suggested using for speed that instead of other attributes. If needed we can do a remapping before assigning the object but the point is that you should only provide an array of strings (or numbers) unless we provide support for a `label` in the future. We currently don't have this so we shouldn't be using the `id` object syntax anyway.

**Comment by tonytlwu** [comment]
@squallstar 

I realised that `disabled` for checkboxes and radio are way less common anyway, so that's fine.

I suggest doing a mapping between `value` and `id`. When I heard you said:

> The form builder internally uses `id` because **Vue**

...all I could think of was...

> Developers shouldn't need to know how it's built.

Yes I agree the following scenario will be used more:

```js
form.field('foo').options([ 'hello', 'world'  ]);
```

But since you've suggested this syntax too:

```js
form.field('foo').options([ { id: 'hello', disabled: true }, { id: 'world' }  ]);
```

...I suggest using...

```js
form.field('foo').options([ { value: 'hello', disabled: true }, { value: 'world' }  ]);
```

...because it'd make more sense. Other attributes such as `label`, as you said, can be added later.

**Comment by squallstar** [comment]
@tonytlwu done, you can now use either `id` or `value`

**Comment by tonytlwu** [comment]
@squallstar I've changed the description to use only `value`. I understand `id` is allowed but having documentation that says *you can use any of these* only confuses people :)

**Pull request merged**
