### PR TITLE
Setting default checkboxes values now works correctly

### PR DESCRIPTION
**Pull request by MaksymShokin**
@sofiiakvasnevska 

## Issue
https://github.com/Fliplet/fliplet-studio/issues/5417

## Description
The user is not able to select multiple checkboxes default values.

## Screenshots/screencasts
checkboxes

## Backward compatibility
This change is fully backward compatible.

### CODE REVIEW

**Comment by squallstar** [comment]
where it the code that splits the value by newline whenever the input changes?

**Comment by MaksymShokin** [comment]
@squallstar 
I did not understand the question. Value splits in line 61 in checkbox.js.

**Comment by squallstar** [comment]
@MaksymShokin that line seem responsible for setting an existing value on the form. What about when the user is actually typing more default values here https://github.com/Fliplet/fliplet-widget-form-builder/pull/277/files#diff-363e1f42405d0c0c5f18b227721e90fcR3

Have you confirmed whether new values are correctly saved in the settings? I would have expected that input to save the input value as an array instead of a string.

**Comment by MaksymShokin** [comment]
@squallstar 
The logic behind it is that if the user sets default value (though textarea you've highlighted), it is technically a string, therefore it will be splitted to an array. If the user sets value though code or has selected any value, split code would not run. I checked and the value saves correctly

**Pull request merged**
