### PR TITLE
OD-240 [Fix] Revert outdated PR

### PR DESCRIPTION
**Pull request by AndrRyaz**
@sofiiakvasnevska 
## Issue
OD-240 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-240
## Description
Revert outdated PRs on Form builder WCAG

https://github.com/Fliplet/fliplet-widget-form-builder/pull/321
https://github.com/Fliplet/fliplet-widget-form-builder/pull/329
https://github.com/Fliplet/fliplet-widget-form-builder/pull/328

## Backward compatibility
This change is fully backward compatible.
## Reviewers
@upplabs-alex-levchenko

### CODE REVIEW

**Comment by AndrRyaz** [comment]
@tonytlwu sorry, but i don't know which screencast i should add to this pr

**Comment by tonytlwu** [comment]
And why are we reverting it? I see it points to https://weboo.atlassian.net/browse/OD-240 but it doesn't specify why we're reverting it.

**Comment by AndrRyaz** [comment]
@tonytlwu because this pr's are blocking the deployment features and i got this from this tasks https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-238

**Review by tonytlwu — DISMISSED** [review]
@sofiiakvasnevska This is ready for testing

Risk: Low
Affected: Focussable UI elements
Verify: Affected UI look correct

Squash and merge: Revert

**Comment by AndrRyaz** [comment]
@tonytlwu sorry, i added one more commit with code revert

**Review by tonytlwu — APPROVED** [review]

**Pull request merged**
