### PR TITLE
don't populate password when updating an entry

### PR DESCRIPTION
**Pull request by squallstar**

### CODE REVIEW

**Comment by tonytlwu** [comment]
Nice and simple 👍 

Is this for both:

* Restoring progress from a previous session; and
* Restoring data from the data source

**Comment by squallstar** [comment]
@tonytlwu the "restoring progress from a previous session" part is already done and it uses this boolean to define whether the field progress can be saved and restored https://github.com/Fliplet/fliplet-widget-form-builder/blob/109c234b081492d667ba3927586717cc90a51679/js/components/password.js#L29-L32

**Comment by squallstar** [comment]
@tonytlwu actually, I'm going to merge this PR into the other one because I think it might have some conflicts.

**Comment by squallstar** [comment]
Merged to https://github.com/Fliplet/fliplet-widget-form-builder/commit/7a71415266b76b5bd07da673f2983d6667c3db57

**Pull request closed without merging**
