### PR TITLE
[Feature] Form builder accessibility

### PR DESCRIPTION
**Pull request by MaksymShokin**
@sofiiakvasnevska

## Issue
Fliplet/fliplet-studio#6422

## Description
Added styles that will highlight the selected input.

## Screencast
https://streamable.com/i1j16p

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

### CODE REVIEW

**Comment by tonytlwu** [comment]
I agree with what @squallstar said. `outline` pretty much supports the same values as `border` and it'll affect the page layout less.

**Comment by MaksymShokin** [comment]
Fixed.

**Comment by squallstar** [comment]
@MaksymShokin can you update the original video with the updated version showing the changes?

**Comment by MaksymShokin** [comment]
@squallstar 
Here is a new look. I changed buttons focus from outline to changing text color because outline doesnot look good on buttons. 
https://streamable.com/jxl7oi

**Comment by squallstar** [comment]
I think the problem with changing the button text is that such button colour can be customised via the app appearance settings. If I change the background colour to #333 then the label becomes invisible. 

@tonytlwu what do you think? I think we should stick to using the outline and optionally make the font-weight bold when the button is focused. Alternative, we can even try a slight scale up via the CSS transform (e.g. `scale(1.05, 1.05)`) but we don't use that visual language so I'm not that keen about exploring such option.

**Comment by tonytlwu** [comment]
I think outline should be fine. I'm not sure why outline wouldn't look good. And when everything else is using outlines, having one UI not using outlines creates inconsistency.

**Comment by MaksymShokin** [comment]
@tonytlwu @squallstar 
By not looking good I mean this. We cannot add corner radius to outline. Therefore it looks like this. 
Capture

**Comment by squallstar** [comment]
What about using the browser's default:

- https://stackoverflow.com/questions/20609485/what-is-the-default-style-of-the-blue-focus-outline-in-chrome/51358900
- http://jsfiddle.net/CXUpm/916/

**Comment by tonytlwu** [comment]
I see. Use `box-shadow` instead then.

**Comment by MaksymShokin** [comment]
@tonytlwu @squallstar 
To make everything correctly with outline we need to add an extra function on the label, like this.
outline 1
outline 2

Maybe it would be simpler to use border instead of outline? Therefore we would not need to add extra function.

**Comment by tonytlwu** [comment]
@MaksymShokin The `html` tag has `context-build` and `context-interface` classes that you can use, depending on if it's in an app preview or Studio interface.

**Comment by tonytlwu** [comment]
We can't use `border` because UI would sometimes already have its own set of borders. We can't use `outline` because it doesn't follow the border radius set by the user.

User `box-shadow`.

You can add a new function, but do not use the jQuery selector with a `#` ID. You should be able to use the VueJS `v-el` markup to define and access a node.

**Comment by MaksymShokin** [comment]
I create new PR for this task, too many conflicts

**Pull request closed without merging**
